### ISSUE TITLE
File system scheme 'queue' not implemented

### ISSUE THREAD

**Issue by 1202zhyl** [flink-extended/dl-on-flink#696]
### Describe the bug
1. follow the [quick_start](https://github.com/flink-extended/dl-on-flink/blob/master/doc/quick_start.md) tutorial
2. submit flink job on local cluster
3. task manager output log: File system scheme 'queue' not implemented (file: ......)
Am I missing something ?
#### Operating system
CentOS 7
flink 1.14.3
TensorFlow 1.15.5

#### Python version
Python 3.7

### Additional context
Tensorflow.python.framework.errors_impl.UnimplementedError: From /job:worker/replica:0/task:0:
File system scheme 'queue' not implemented (file: 'queue:///tmp/1644377004835-1/queue-5118498194079552779.output:8392704')
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNext]]

**Comment by Sxnan** [comment]
Hi @1202zhyl, thanks for reporting the issue. I have investigated the problem. It turns out that Tensorflow has [issue](https://github.com/tensorflow/tensorflow/issues/31807) loading a Manylinux custom op. 

I have uploaded the new snapshot wheel. Could you uninstall the `flink-ml-framework` and `flink-ml-tensorflow` and try follow the quick start again. Also make sure that the flink-ml-tensorflow version is `0.4.dev20220209`.

#698 should fix this problem.

**Comment by 1202zhyl** [comment]
@Sxnan I have tried again following what u said and it works like a charm. Thanks a loooooot!
